# Porta do servidor
server.port=9000

# Nome da aplicação
spring.application.name=auth-server-lab

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://promise-birth-disc-northeast.trycloudflare.com/realms/lab-realm

# Logs de segurança (muito importante para debug)
logging.level.org.springframework.security=INFO

